Repository depromeet/street-drop-iOS, pull requests merged in 2023-06, with the labels that each got.

#90 ✨마이페이지 화면 및 기능 구현
  StreetDrop/StreetDrop.xcodeproj/project.pbxproj
  StreetDrop/StreetDrop/Presentation/MyPage/View/InfoTableViewCell.swift
  StreetDrop/StreetDrop/Presentation/MyPage/View/MyPageViewController.swift
  StreetDrop/StreetDrop/Presentation/MyPage/ViewModel/MyPageViewModel.swift
  StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/SearchingMusicViewController.swift
  StreetDrop/StreetDrop/Util/Constant/MyPageInfo.swift
Labels: Feature

#123 Feature/드랍화면 주소 안들어오는 문제 해결
  StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
Labels: Bug

#136 ✨500m 반경 내 POI 마커만, 클릭 시, 상세정보 API를 호출하여 반경 내 음악들의 다이얼 UI가 나타나도록 구현
  StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
  StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
Labels: Request

#141 ✨내 위치 버튼 기능 및 UI 추가
  StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
  StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
  StreetDrop/StreetDrop/Resource/Assets.xcassets/myLocationButton.imageset/Contents.json
  StreetDrop/StreetDrop/Resource/Assets.xcassets/myLocationButton.imageset/myLocation@1x.png
  StreetDrop/StreetDrop/Resource/Assets.xcassets/myLocationButton.imageset/myLocation@2x.png
  StreetDrop/StreetDrop/Resource/Assets.xcassets/myLocationButton.imageset/myLocation@3x.png
Labels: Request
