Repository depromeet/street-drop-iOS, pull requests merged in 2023-07, with the labels that each got.

#161 🐛음악 검색 텍스트 뷰 공백일 경우, 이전 검색어에대한 테이블뷰 정보 지우도록 수정
  StreetDrop/StreetDrop/Presentation/SearchingMusicScene/View/SearchingMusicViewController.swift
  StreetDrop/StreetDrop/Presentation/SearchingMusicScene/ViewModel/SearchingMusicViewModel.swift
Labels: Bug

#174 Feature/data 세개 이하 인덱스문제
  StreetDrop/StreetDrop/Presentation/CommunityView/ViewModel/CommunityViewModel.swift
Labels: Hotfix

#177 🐛 장르 라벨 많을 때, 옵션버튼 가림문제해결
  StreetDrop/StreetDrop/Presentation/CommunityView/View/CommunityViewController.swift
Labels: Bug

#205 🐛대한민국 전체 poi 나타나도록 수정
  StreetDrop/StreetDrop/Presentation/MainScene/ViewModel/MainViewModel.swift
Labels: Bug

#207 ✨지도 줌 아웃 레벨, 지도 영역 제한
  StreetDrop/StreetDrop/Presentation/MainScene/View/MainViewController.swift
Labels: Request

#209 ✨2차 배포 앱로고 변경
  StreetDrop/StreetDrop/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.jpeg
  StreetDrop/StreetDrop/Resource/Assets.xcassets/AppIcon.appiconset/AppIcon.jpg
  StreetDrop/StreetDrop/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Request
